spring:
    application:
        name: users-service

server:
    port: ${port:8095}

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-discovery-service.cfapps.io/eureka/
    registerWithEureka: true

security:
  basic:
    enable: false

management:
  security:
    enabled: false