spring:
    application:
        name: sessions-service

server:
    port: 8094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true

security:
  basic:
    enable: false

management:
  security:
    enabled: false