spring:
    application:
        name: sessions-service

server:
    port: ${port:8094}

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-discovery-service.cfapps.io/eureka/
    registerWithEureka: true

security:
  basic:
    enable: false
  ignored: /**

management:
  security:
    enabled: false