spring:
    application:
        name: gateway-service

info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  SendErrorFilter:
      error:
        disable: true
  prefix: /api
  routes:
    questions:
      path: /questions/**
      serviceId: questions-service
      stripPrefix: false
    answers:
          path: /answers/**
          serviceId: answers-service
          stripPrefix: false
    sessions:
              path: /sessions/**
              serviceId: sessions-service
              stripPrefix: false

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

security:
  basic:
    enable: false

management:
  security:
    enabled: false

auth-config:
  serviceApiMap:
    questions:
      - method: POST
        url: /api/questions/*
      - method: POST
        url: /api/questions/*/upvote
      - method: POST
        url: /api/questions/*/upvote
      - method: PUT
        url: /api/questions/*



#security:
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:8099/uaa/oauth/token
#      userAuthorizationUri: http://localhost:8099/uaa/oauth/authorize
#      clientId: agilefaqs
#      clientSecret: agilefaqssecret
#    resource:
#      userInfoUri: http://localhost:8099/uaa/user
#      preferTokenInfo: false
#  sessions: ALWAYS