spring:
    application:
        name: gateway-service

info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false


hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

zuul:
  ribbonIsolationStrategy: THREAD
  prefix: /api
  routes:



server:
  port: ${port:8765}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

security:
  basic:
    enable: false
  ignored: /**

management:
  security:
    enabled: false

