spring:
    application:
        name: gateway-service

info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  SendErrorFilter:
      error:
        disable: true
  prefix: /api
  routes:
    questions:
      path: /questions/**
      serviceId: questions-service
      stripPrefix: false
    answers:
          path: /answers/**
          serviceId: answers-service
          stripPrefix: false
    search:
          path: /search/**
          serviceId: search-service
          stripPrefix: false
    users:
          path: /users/**
          serviceId: users-service
          stripPrefix: false
    sessions:
          path: /sessions/**
          serviceId: sessions-service
          stripPrefix: false

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

security:
  basic:
    enable: false

management:
  security:
    enabled: false

auth-config:
  serviceApiMap:
    questions:
      - method: POST
        url: /api/questions/*
      - method: POST
        url: /api/questions/*/upvote
      - method: POST
        url: /api/questions/*/downvote
      - method: PUT
        url: /api/questions/*
    answers:
      - method: POST
        url: /api/answers/*
      - method: POST
        url: /api/answers/*/upvote
      - method: POST
        url: /api/answers/*/downvote
      - method: PUT
        url: /api/answers/*
    users:
      - method: GET
        url: /api/users/*
