spring:
  application:
    name: eureka-discovery-service

    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true
    eviction-interval-timer-in-ms: 1000