tomcat:
 server.tomcat.max-threads: 100

spring:
  application:
    name: eureka-discovery-service

server:
  port: ${PORT:8761}
  tomcat.max-threads: 100
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  