spring:
    application:
        name: answers-service

server:
    port: ${port:8092}

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-discovery-service.cfapps.io/eureka/
    registerWithEureka: true


security:
  basic:
    enable: false

management:
  security:
    enabled: false