spring:
    application:
        name: answers-service
    cloud:
        services:
          registrationMethod: route

server:
    port: ${port:8092}


security:
  basic:
    enable: false
  ignored: /**

management:
  security:
    enabled: false