spring:
    application:
        name: answers-service

server:
    port: ${port:8092}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true


security:
  basic:
    enable: false

management:
  security:
    enabled: false