spring:
    application:
        name: agilefaqs-questions-service

server:
    port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
