spring:
    application:
        name: questions-service

server:
    port: 8091
    tomcat:
      accesslog:
        enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true


security:
  basic:
    enable: false

management:
  security:
    enabled: false