spring:
    application:
        name: search-service

server:
    port: ${port:8093}

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-discovery-service.cfapps.io/eureka/
    registerWithEureka: true


security:
  basic:
    enable: false
  ignored: /**

management:
  security:
    enabled: false